##
## Payjoin config.toml configuration file. Lines beginning with # are comments.
##

# Common Settings
# --------------

# The path to the database file
db_path = "payjoin.db"

# The maximum fee rate that the receiver is willing to pay (in sat/vB)
max_fee_rate = 2.0

# Bitcoin RPC Connection Settings
# ------------------------------
[bitcoind]
# The RPC host of the wallet to connect to.
# For example, if the wallet is "sender", then default values are:
# 	- mainnet: http://localhost:8332/wallet/sender
# 	- testnet: http://localhost:18332/wallet/sender
# 	- regtest: http://localhost:18443/wallet/sender
# 	- signet: http://localhost:38332/wallet/sender
rpchost = "http://localhost:18443/wallet/sender"

# The RPC .cookie file used only for local authentication to bitcoind.
# If rpcuser and rpcpassword are being used, this is not necessary.
# Found in data directory, which is located:
#	Linux: ~/.bitcoin/<NETWORK>/.cookie
# 	MacOS: ~/Library/Application Support/Bitcoin/<NETWORK>/.cookie
# 	Windows Vista and later: C:\Users\YourUserName\AppData\Roaming\Bitcoin\<NETWORK>\.cookie
# 	Windows XP: C:\Documents and Settings\YourUserName\Application Data\Bitcoin\<NETWORK>\.cookie
cookie = ""

# The rpcuser to connect to (specified in bitcoin.conf).
rpcuser = "user"

# The rpcpassword of the user to connect to (specified in bitcoin.conf).
rpcpassword = "password"

# Version Configuration
# -------------------
# Uncomment ONE of the following version configurations depending on which version you want to use

# Version 1 Configuration
# [v1]
# port = 3000
# pj_endpoint = "https://localhost:3000"

# Version 2 Configuration
# [v2]
# pj_directory = "https://payjo.in"
# ohttp_relay = "https://pj.bobspacebkk.com"
# # Optional: The HPKE keys which need to be fetched ahead of time from the pj_endpoint
# # for the payjoin packets to be encrypted.
# # These can now be fetched and no longer need to be configured.
# ohttp_keys = "./path/to/ohttp_keys"
