# The RPC host of the wallet to connect to.
# For example, if the wallet is "sender", then default values are:
# 	- mainnet: http://localhost:8332/wallet/sender
# 	- testnet: http://localhost:18332/wallet/sender
# 	- regtest: http://localhost:18443/wallet/sender
# 	- signet: http://localhost:38332/wallet/sender
# 
bitcoind_rpchost=
# ---
# The RPC .cookie file used only for local authentication to bitcoind.
# If rpcuser and rpcpassword are being used, this is not necessary.
# Found in data directory, which is located:
#	Linux: ~/.bitcoin/<NETWORK>/.cookie
# 	MacOS: ~/Library/Application Support/Bitcoin/<NETWORK>/.cookie
# 	Windows Vista and later: C:\Users\YourUserName\AppData\Roaming\Bitcoin\<NETWORK>\.cookie
# 	Windows XP: C:\Documents and Settings\YourUserName\Application Data\Bitcoin\<NETWORK>\.cookie

bitcoind_cookie=
# ---
# The rpcuser to connect to (specified in bitcoin.conf).

# bitcoind_rpcuser=
# ---
# The rpcpassword of the user to connect to (specified in bitcoin.conf)

bitcoind_rpcpassword=
# ---
# The payjoin endpoint which coordinates the transaction. In v2, this is the payjoin directory

pj_endpoint=
# ---
# (v2 only) The OHTTP relay which proxies requests to the OHTTP Gateway -> pj_endpoint

ohttp_relay=
# ---
# (v2 only, optional) The OHTTP HPKE keys used to encrypt communcation between the OHTTP relay and gateway

ohttp_keys=
# ---
# (v1 only) The port for v1 receiving servers to bind to.

port=

