[package]
name = "payjoin-client"
version = "0.1.0"
authors = ["Dan Gould <d@ngould.dev>", "Martin Habovstiak <martin.habovstiak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
payjoin = { path = "../payjoin", features = ["sender", "receiver"] }
bitcoincore-rpc = "0.14.0"
rand = "0.6.5"
reqwest = { version = "0.11.4", features = ["blocking"] }
base64 = "0.13.0"
clap = "2.33.3"
turn = "0.6.1"
tokio = { version = "1.6.1", features = ["full"] }
webrtc-util = { version = "0.7.0", default-features = false, features = ["conn", "vnet"] }
noiseexplorer_nnpsk0 = { path = "../nnpsk0" }