name: Test and Build

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.63.0 # MSRV
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Fixes for MSRV
        if: matrix.rust == '1.63.0'
        run: |
          cargo update
          cargo update -p clap_lex --precise 0.3.0
          cargo update -p regex --precise 1.9.6
          cargo update -p url --precise 2.5.0
          cargo update -p which --precise 4.4.0
          cargo update -p time@0.3.36 --precise 0.3.20
          cargo update -p reqwest --precise 0.12.4
      - name: test payjoin lib
        run: cargo test --package payjoin --verbose --all-features --lib
      - name: test payjoin v1 integration
        run: cargo test --package payjoin --verbose --features=send,receive --test integration
      - name: test payjoin v2 integration
        run: cargo test --package payjoin --verbose --features=send,receive,danger-local-https,v2 --test integration
      - name: test payjoin-cli bin v2
        run: cargo test --package payjoin-cli --verbose --features=danger-local-https,v2 --test e2e
      - name: test payjoin-cli bin v1
        run: cargo test --package payjoin-cli --verbose --features=danger-local-https

  fmt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [payjoin, payjoin-cli]

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: fmt check
        run: |
          cd ${{ matrix.package }}
          cargo fmt --all -- --check
